vim.keymap.set('n', '<leader>t', '<cmd>ToggleTerm direction=horizontal<cr>', {})
-- vim.keymap.set('t', '<esc>', [[<C-\><C-n>]], opts)
-- vim.keymap.set('t', 'jk', [[<C-\><C-n>]], opts)
-- vim.keymap.set('t', '<C-h>', [[<cmd>wincmd h<CR>]], opts)
-- vim.keymap.set('t', '<S-j>', [[<cmd>wincmd j<CR>]], opts)
vim.keymap.set('t', '<S-k>', [[<cmd>wincmd k<CR>]], opts)
-- vim.keymap.set('t', '<C-l>', [[<cmd>wincmd l<CR>]], opts)
-- vim.keymap.set('t', '<C-w>', [[<C-\><C-n><C-w>]], opts)
